# Generated by Django 2.1.2 on 2018-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Cin',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
