# Generated by Django 2.1.2 on 2018-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_auto_20181103_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
