# Generated by Django 2.1.2 on 2018-11-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_auto_20181103_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
