# Generated by Django 2.1.2 on 2018-11-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Photo',
        ),
    ]
